#!/bin/bash
# Enable a BlockHead site by copying its generated nginx config and reloading nginx.
# Usage: sudo ./scripts/enable_site.sh <domain>
# Example: sudo ./scripts/enable_site.sh example.com
# The script expects the nginx config generated by BlockHead to exist in
# generated_configs/<domain>.

set -e

DOMAIN="$1"
if [ -z "$DOMAIN" ]; then
  echo "Usage: sudo ./scripts/enable_site.sh <domain>" >&2
  exit 1
fi

CONFIG_DIR="$(dirname "$0")/../generated_configs"
SOURCE="$CONFIG_DIR/$DOMAIN"
TARGET="/etc/nginx/sites-available/$DOMAIN"

# Ensure the config file exists before attempting to copy
if [ ! -f "$SOURCE" ]; then
  echo "Config $SOURCE not found" >&2
  exit 1
fi

# Copy config to nginx directory
sudo cp "$SOURCE" "$TARGET"
# Create or update symlink in sites-enabled
sudo ln -sf "$TARGET" "/etc/nginx/sites-enabled/$DOMAIN"
# Reload nginx to apply the changes
sudo systemctl reload nginx

echo "Site $DOMAIN enabled and nginx reloaded."
